# Generated by Django 5.0.6 on 2024-07-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0002_alter_chat_created_at_alter_chatmember_joined_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
